### ISSUE TITLE
crash server onquit player

### ISSUE THREAD

**Issue by SuperKali** [NL-4-DEVS/Eggwars#14]
The server just shuts off a player in the waiting lobby goes out

**Comment by Driesboy** [comment]
picture plzz

**Comment by SuperKali** [comment]
ok

**Comment by SuperKali** [comment]
[https://youtu.be/qlpbSdxQDcQ](url)

**Comment by Driesboy** [comment]
i cant see it

**Comment by Driesboy** [comment]
its private

**Comment by SuperKali** [comment]
please contact me on telegram @superkali

**Comment by SuperKali** [comment]
please give me to email

**Comment by Driesboy** [comment]
Coenendries3@gmail.com

Op 23-apr.-2017 23:54 schreef "SuperKali" <notifications@github.com>:

**Comment by SuperKali** [comment]
ok sent!

**Comment by Driesboy** [comment]
send a mail back

Op 24-apr.-2017 18:29 schreef "SuperKali" <notifications@github.com>:

**Comment by Driesboy** [comment]
https://github.com/NL-4-DEVS/Eggwars/tree/fix-%2314
can you test this one??

**Comment by Driesboy** [comment]
this one for api3 https://github.com/NL-4-DEVS/Eggwars/tree/API3-Fix-%2314

**Comment by SuperKali** [comment]
OK I'm ready to test it

**Comment by SuperKali** [comment]
Notice: Undefined variable: main in /root/EggWars-Server2/plugins/Eggwars-API3-Fix-14/src
Driesboy/EggWars/EventListener.php on line 38
[05:18:11] [Server thread/CRITICAL]: Could not pass event 'pocketmine\event\player\Player
uitEvent' to 'EggWars v1': Call to a member function IsInArena() on null on Driesboy\EggW
rs\EventListener
[05:18:11] [Server thread/CRITICAL]: Error: "Call to a member function IsInArena() on nul
" (EXCEPTION) in "/plugins/Eggwars-API3-Fix-14/src/Driesboy/EggWars/EventListener" at lin
 38

**Comment by SuperKali** [comment]
IsInArena () is null

**Comment by Driesboy** [comment]
fixed

**Comment by Driesboy** [comment]
check again

**Comment by SuperKali** [comment]
Warning: Invalid argument supplied for foreach() in /root/EggWars-Server2/plugins/Eggwars
API3-Fix-14/src/Driesboy/EggWars/EggWars.php on line 206

 The server does not shut down but warns of this error

**Comment by Driesboy** [comment]
will check this after school

Op 26-apr.-2017 07:37 schreef "SuperKali" <notifications@github.com>:

**Comment by SuperKali** [comment]
Ok

**Comment by Driesboy** [comment]
But its working

**Comment by SuperKali** [comment]
The plugin now works but from that console error!

I sent the error on your e-mail

**Comment by SuperKali** [comment]
Check the email

**Comment by Driesboy** [comment]
checked but its not a very important bugg

**Comment by Driesboy** [comment]
test again i think i fixed it

**Comment by SuperKali** [comment]
Ok

**Comment by Driesboy** [comment]
working???

**Comment by SuperKali** [comment]
yes working

Notice: Undefined property: Driesboy\EggWars\EggWars::$b in /root/EggWars-Server2/plugins/Eggwars-3b5e75402dba8f9cd731aad30cc921e62ee0aa60/src/Driesboy/EggWars/Task/Game.php on line 130

**Comment by SuperKali** [comment]
and add knock sign?
