### ISSUE TITLE
add knockback sign

### ISSUE THREAD

**Issue by Driesboy** [NL-4-DEVS/Eggwars#16]

**Comment by Lazerplayz** [comment]
I could add sign knockback is you still need to add it

**Comment by Driesboy** [comment]
ok is good

**Comment by Driesboy** [comment]
but in the direction from the sign

**Comment by Lazerplayz** [comment]
Ill try

**Comment by Lazerplayz** [comment]
How stong does it have to be? It could just be a luttle knock off the sign and therefore you wont be flung everywhere

**Comment by Driesboy** [comment]
2 blocks

**Comment by Driesboy** [comment]
@Lazerplayz is it done??

**Comment by Lazerplayz** [comment]
@Driesboy nearly done

**Comment by Driesboy** [comment]
On

**Comment by Lazerplayz** [comment]
Opps, totally didn't forget about this xD

**Comment by minlack0189** [comment]
how to create sign?

**Comment by Driesboy** [comment]
@Lazerplayz i am waiting

**Comment by Lazerplayz** [comment]
@Driesboy sorry about that I will send you the line of code and you can implement it, I've been studying alot lately.

**Comment by Lazerplayz** [comment]
@Driesboy close this issue and remind me this VIA twitter.

**Comment by Driesboy** [comment]
can you make a pr now??
