### ISSUE TITLE
bug sign

### ISSUE THREAD

**Issue by SuperKali** [NL-4-DEVS/Eggwars#22]
Is in play but there is no player in it
![30tkuhi](https://cloud.githubusercontent.com/assets/15795262/25561880/2e52da6e-2d75-11e7-83b4-f3ff0c26bb6e.jpg)

**Comment by Driesboy** [comment]
I know this

**Comment by Driesboy** [comment]
i know but i dont now what the hell the error is

**Comment by Lazerplayz** [comment]
https://github.com/NL-4-DEVS/Eggwars/blob/master/src/Driesboy/EggWars/Task/SignManager.php#L45 Maybe around here?

**Comment by Driesboy** [comment]
but its not every restart

**Comment by Driesboy** [comment]
i dont have this bug enymore
