### ISSUE TITLE
Add Spectator Mode

### ISSUE THREAD

**Issue by SuperKali** [NL-4-DEVS/Eggwars#27]
It would be nice to add the viewer mode when the game is in play to give players the chance to see the game

**Comment by Driesboy** [comment]
yeah but its realy difficult

**Comment by SuperKali** [comment]
Yes I believe

**Comment by Lazerplayz** [comment]
@Driesboy no its not difficult you just need to know how to add it into the plugin 😁

**Comment by Driesboy** [comment]
fixing it soon

**Comment by Lazerplayz** [comment]
@Driesboy don't you mean. Adding it soon? :P

**Comment by Driesboy** [comment]
can you read :P

**Comment by Lazerplayz** [comment]
Oi no editing that's cheating 😂

**Comment by Kenner-G** [comment]
To be honest, you can make a glass ceiling and make a simple /spectate command to teleport you there lol.
