### ISSUE TITLE
Put A Team Color List

### ISSUE THREAD

**Issue by ExplodingSquad** [NL-4-DEVS/Eggwars#28]
I Need All Team Colors For /ew set myarena [color] i need all color code pls open this pull request

**Comment by Driesboy** [comment]
"ORANGE" => "§6",
      "PURPLE" => "§d",
      "LIGHT-BLUE" => "§b",
      "YELLOW" => "§e",
      "GREEN" => "§a",
      "GRAY" => "§7",
      "BLUE" => "§9",
      "RED" => "§c"

**Comment by ExplodingSquad** [comment]
Not Working
