### ISSUE TITLE
how to setup a team IDK How

### ISSUE THREAD

**Issue by ExplodingSquad** [NL-4-DEVS/Eggwars#29]
idk how to do this if i /ew set (Myarena) §e It Not Working

**Comment by ExplodingSquad** [comment]
I It Not Working It Just Say Team You Can Use REDRED

**Comment by Driesboy** [comment]
All in cappital

Op 3-mei-2017 08:08 schreef "ExplodingSquad" <notifications@github.com>:

**Comment by ExplodingSquad** [comment]
Do I Need To Add The § Colors

**Comment by Driesboy** [comment]
nooooooooo

Op 3-mei-2017 10:15 schreef "ExplodingSquad" <notifications@github.com>:

**Comment by ExplodingSquad** [comment]
![screenshot_2017-05-03-16-28-51](https://cloud.githubusercontent.com/assets/25544986/25653096/faaf33c8-301d-11e7-90b2-936f4ecfe46f.png)
![screenshot_2017-05-03-16-30-02](https://cloud.githubusercontent.com/assets/25544986/25653100/fe382e3c-301d-11e7-863c-8ee2c4251803.png)


Is This Correct Or The Wrong is The Plugin
