### ISSUE TITLE
Wont Work At Bluelight 1.0.7 phar

### ISSUE THREAD

**Issue by ExplodingSquad** [NL-4-DEVS/Eggwars#32]
Tesseract Crash Dump Wed May 3 07:44:51 ACT 2017

Error: mkdir(): File exists
File: /EGGWARS.phar/src/Driesboy/EggWars/EggWars
Line: 292
Type: E_WARNING

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN : EggWars v1

Code:
[283]         $o->sendMessage("§8» §fTeams you can use: \n$Team");
[284]       }
[285]     }else{
[286]       $o->sendMessage("§8» §cThere is no such arena.");
[287]     }
[288]   }
[289] 
[290]   public function copy($source, $target){
[291]     $directory = opendir($source);
[292]     @mkdir($target);
[293]     while (false !== ($file = readdir($directory))){
[294]       if ($file != "." && $file != "..") {
[295]         if (is_dir($source.'/'.$file)) {
[296]           $this->copy($source.'/'.$file, $target.'/'.$file);
[297]         } else {
[298]           copy($source.'/'.$file, $target.'/'.$file);
[299]         }
[300]       }
[301]     }
[302]     closedir($directory);

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

Tesseract version: 0000000000000000000000000000000000000000 [Protocol 105; API 3.0.0]
uname -a: Windows NT VULCAN 10.0 build 14393 (Windows 10) AMD64
PHP version: 7.0.2
Zend version: 3.0.0
OS : WINNT, win

Server uptime: 19 minutes 7 seconds
Number of loaded worlds: 5
Players online: 0/30

Loaded plugins:
1vs1 0.0.5 by  for API(s) 1.0.0, 1.1.0
AdminFun 1.0.0 by hoyinm14mc for API(s) 1.12.0, 1.13.0, 2.0.0
AlwaysSpawn 2.2.2 by Philip Shilling for API(s) 1.12.0
Prealms_BuildBattle 1.3.0 by DragonPlayzMC for API(s) 1.0.0, 2.0.0
Cameraman 1.1 by ChalkPE for API(s) 1.12.0, 1.13.0, 2.0.0
ClearLagg 1.1.0 by LegendOfMCPE for API(s) 1.0.0
DrawMyThing 1.0.0 by  for API(s) 1.1.0
EconomyAPI 2.0.9 by onebone for API(s) 3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5, 3.0.1, 3.0.2
EggWars 1 by Driesboy for API(s) 3.0.0-ALPHA4, 3.0.0-ALPHA5, 3.0.0, 3.0.1
ManyWorlds 2.0.3 by aliuly for API(s) 2.0.0, 1.13.0, 3.0.0-ALPHA1
NPC 1.4 by onebone for API(s) 2.0.0, 2.1.0, 3.0.0-ALHA1, 3.0.0-ALPHA2, 3.0.0-ALHA3
UnlimitedSlots 1.0.0 by Gumbrat-And-TheDeibo for API(s) 1.14.0
PurePerms 1.3.5 by 64FF00 for API(s) 1.13.0, 2.0.0
ServerAuth 2.13 by EvolSoft for API(s) 1.11.0
Slapper 1.3.3 by jojoe77777 for API(s) 3.0.0-ALPHA4
StatsMe 2.1.0 by  for API(s) 1.14.0, 2.0.0
TimeCommander 2.1 by LDX for API(s) 1.0.0, 2.0.0
TNTRun 1.0.0 by BukkitPlaysMC for API(s) 1.0.0
WorldEdit 3.2 by ByZikenPE for API(s) 1.13.0
PureChat 1.4.0 by 64FF00 for API(s) 1.13.0, 2.0.0
SimpleWarp v3.2.0 by Falkirks for API(s) 2.0.0
SkyBlock 1.0.2 by thebigsmileXD mwvent Wies and Exxarion for API(s) 2.0.0, 3.0.0, 3.0.0-ALPHA4, 3.0.0-ALPHA5

**Comment by Driesboy** [comment]
i dont have this bug
when you got this bug??

**Comment by Driesboy** [comment]
i reopen this if you give more info

**Comment by ExplodingSquad** [comment]
i get this bug in the latest bluelight phar 1.0.7 stable

**Comment by Driesboy** [comment]
What did you do?

**Comment by ExplodingSquad** [comment]
i will report the bug
