### ISSUE TITLE
Players cant break,pvp

### ISSUE THREAD

**Issue by KromeThirty30** [NL-4-DEVS/Eggwars#33]
I installed this plugin to my bluelight server,Players cant break or pvp,but when i remive this plugin,Players can Break/Pvp again..Can you fix this problems? It occurs in all worlds

**Comment by Lazerplayz** [comment]
Is there any errors when a player hits the other player or a crashdump? Elaborate please!

**Comment by Driesboy** [comment]
i have blockbreak in my lobby and other worlds
only the waiting lobby world and the arena world can not be breaked

**Comment by KromeThirty30** [comment]
Theres no errors in consoles. But it occurs in whole server

**Comment by KromeThirty30** [comment]
Help

**Comment by Driesboy** [comment]
Send me your plufin list

**Comment by Lazerplayz** [comment]
@Driesboy you always make the same spelling mistakes as me :O

**Comment by Driesboy** [comment]
lol

**Comment by KromeThirty30** [comment]
Even i reset and remove all the plugins, when i import this, the problem occurs. Im using Bluelight

**Comment by Driesboy** [comment]
my players can pvp btw

**Comment by KromeThirty30** [comment]
Yes, Players can pvp and break/place blocks inside the eggwars arena.but in Creative ,They cant

**Comment by Lazerplayz** [comment]
Uhhh what eggwars is for survival not creative

**Comment by Driesboy** [comment]
There is a block that player cant break blocks that are not placed in the
game so if you buy sandstone you can place it

Op 11-mei-2017 08:59 schreef "KromeThirty30" <notifications@github.com>:

**Comment by ExplodingSquad** [comment]
Yea It Like On My Server Why This Happen

**Comment by Driesboy** [comment]
because we block it
