### ISSUE TITLE
Bug Villager ByPass Item

### ISSUE THREAD

**Issue by SuperKali** [NL-4-DEVS/Eggwars#35]
You can bypass the objects without buying them by putting the object in front of the wool and then bringing it to our inventory

**Comment by Driesboy** [comment]
windows 10?
pocketmine?

**Comment by SuperKali** [comment]
I use Minecraft Windows 10 Beta .
OS : PMMP

**Comment by SuperKali** [comment]
You can bypass only with the classic inventory

**Comment by Driesboy** [comment]
i know it but that is not a bug from this plugin this is a PMMP windows 10 beta bug
