### ISSUE TITLE
Add ban command ingame

### ISSUE THREAD

**Issue by KoalaBoy** [NL-4-DEVS/Eggwars#36]

**Comment by Lazerplayz** [comment]
This is an eggwars plugin not a ban system

**Comment by KoalaBoy** [comment]
I mean ingame player can /sethome or /home

**Comment by Lazerplayz** [comment]
Ah okay

**Comment by Lazerplayz** [comment]
I'll leave this one to @Driesboy

**Comment by KoalaBoy** [comment]
This code from SW_svile
https://pastebin.com/tejdzQXg

**Comment by KoalaBoy** [comment]
And have alot bug with npc shop

**Comment by SuperKali** [comment]
@KoalaBoy What kind of bug?

**Comment by KoalaBoy** [comment]
Player can take everything in shop

**Comment by Driesboy** [comment]
what version? /timings report
