### ISSUE TITLE
Error On Loading Chunk

### ISSUE THREAD

**Issue by SuperKali** [NL-4-DEVS/Eggwars#41]
fix this problem
![minecraft_ windows 10 edition 15_06_2017 12_31_03](https://user-images.githubusercontent.com/19473898/27177407-91c2ce2c-51c6-11e7-8438-4d5fdfffd7de.png)

**Comment by Lazerplayz** [comment]
This is a client end issue there is a "hack" of fixing this if im correct but I need to find it lol
