### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by iZeaoGamer** [NL-4-DEVS/Eggwars#42]
Hey, I have a few suggestions / Bugs you need to fix.

1. Add A option where you can set MinPlayers. Min 2

2. Please Fix a bug where you can't do /ew shop. It says unknown error occured.

3. What do you meen by "Eggs?" Do you mean dragon eggs? Because they aren't implemented into Pocketmine 1.1.0.

**Comment by Driesboy** [comment]
1. CONFIG
2 DUplicate
3. yes do /give player 122 64

**Comment by Driesboy** [comment]
and place it!

**Comment by iZeaoGamer** [comment]
I did. It just doesn't let me place.

**Comment by iZeaoGamer** [comment]
![img_0575](https://user-images.githubusercontent.com/20418886/27606081-a8601432-5b76-11e7-80c4-b121f5b33210.PNG)

**Comment by Driesboy** [comment]
Use blocks api3

Op 27-jun.-2017 21:24 schreef "iZeaoGamer" <notifications@github.com>:

**Comment by iZeaoGamer** [comment]
What do you mean?

**Comment by Driesboy** [comment]
use the blocks/api3 branch

Op 27-jun.-2017 21:29 schreef "iZeaoGamer" <notifications@github.com>:

**Comment by iZeaoGamer** [comment]
Here?
![img_0576](https://user-images.githubusercontent.com/20418886/27606376-e717f9fa-5b77-11e7-9329-287634ef8fca.PNG)
![img_0577](https://user-images.githubusercontent.com/20418886/27606377-e73c6f38-5b77-11e7-9f0e-113d44fbed9f.PNG)

**Comment by Driesboy** [comment]
NOOOO PMMP BLOCKS API3
