### ISSUE TITLE
Error. Cant spawn villager shop

### ISSUE THREAD

**Issue by optimusprime338** [NL-4-DEVS/Eggwars#47]
using latest commit in clearsky 
console error:- 
27.06 02:46:13 [Server] Server thread/CRITICAL ClassNotFoundException: "Class Driesboy\EggWars\Command\FloatTag not found" (EXCEPTION) in "src/spl/BaseClassLoader" at line 144
27.06 02:46:13 [Server] Server thread/CRITICAL Unhandled exception executing command 'ew shop' in ew: Class Driesboy\EggWars\Command\FloatTag not found
Do I need any other plugin?

**Comment by Driesboy** [comment]
Its only for pmmp

Op 27-jun.-2017 10:48 schreef "NASIR HUSSAIN" <notifications@github.com>:

**Comment by optimusprime338** [comment]
Thanks
