### ISSUE TITLE
Commands

### ISSUE THREAD

**Issue by Pitstopers** [NL-4-DEVS/Eggwars#48]
When I do /ew create MG RED BLUE 4 it does not work please help and I can't place the dragon egg btw I'm useing blue light if none of these work you can make this into a bedwars plugin

**Comment by Driesboy** [comment]
RED BLUE?

**Comment by Pitstopers** [comment]
What Colors and my supposed to use

**Comment by Pitstopers** [comment]
Only works on PMMP and BlueLight

**Comment by Pitstopers** [comment]
But blue light don't work for generators

**Comment by Driesboy** [comment]
https://github.com/NL-4-DEVS/Eggwars/blob/master/README.md

**Comment by Driesboy** [comment]
read this

**Comment by Pitstopers** [comment]
Will this ever work for bluelight

**Comment by Driesboy** [comment]
nope
