### ISSUE TITLE
Fix Bug

### ISSUE THREAD

**Issue by DarknessGaming** [NL-4-DEVS/Eggwars#52]
I destroyed the enemy's eggs but nothing happened, the + did not turn into - and the gold level 2 machine did not produce in 6 seconds which took 12-15 seconds.

**Comment by Driesboy** [comment]
Your pc is to slow!!!!

Op 30-jun.-2017 16:57 schreef "DarknessGaming" <notifications@github.com>:

**Comment by DarknessGaming** [comment]
Hey, watch this video
  https://m.youtube.com/watch?v=PPnJvUZn3D8

**Comment by DarknessGaming** [comment]
It's your plugins but someone edited it to make it work better, but it's in Spanish and I hate that.
Sorry, I use google translate so maybe it will be translated incorrectly

**Comment by Driesboy** [comment]
check my server gamecraftpe.tk running on the latest one and it works

**Comment by iZeaoGamer** [comment]
I think it's because EggWars (The plugin Dries made) is on PMMP only. Dries, you should make it compatible with all server softwares. No need to only add one software. PMMP is too buggy for me, so I use Genisyspro.
