### ISSUE TITLE
Bugs which may / may not be fixed yet

### ISSUE THREAD

**Issue by iZeaoGamer** [NL-4-DEVS/Eggwars#59]
So, I've found a couple of bugs (Not with the latest, the one you've just released.) But in another build.
1. Dragon egg - When you break the dragon egg (In the game) it doesn't say the message that someone broke the egg.

2. Cannot place / break blocks when not in the world or game - When you aren't in the EggWars game, non ops can't place or break blocks. We have a skywars plugin for example, people can't play it because we have EggWars installed. Not sure if it was the version I was using, as it wasn't made by you. It was by another user.
Thanks. Hope to get a reply back.

**Comment by iZeaoGamer** [comment]
Can you not edit my post and reply to me.

**Comment by Driesboy** [comment]
you dont need to break the egg you need to tapp it

i know that is normal you can not run eggwars and skywars in the same server!
