### ISSUE TITLE
[Question] would this work on GenisysPro?

### ISSUE THREAD

**Issue by mote166** [NL-4-DEVS/Eggwars#60]

**Comment by Driesboy** [comment]
Close #60
Nope

Op 16-jul.-2017 20:27 schreef "mote166" <notifications@github.com>:

**Comment by mote166** [comment]
i tried it everything was good except that once i join the server it doesn't spawn me in the main level even when i set Mspawns to force hub me im still in the game world but the coords are the same as the main world coords

**Comment by mote166** [comment]
please make a new branch for pmmp forks

**Comment by TheFixerDevelopment** [comment]
Don't worry. I will allow forks to come into place. Soon, Forks will be compatible.

**Comment by TheFixerDevelopment** [comment]
It does now. Download the GenisysPro version of the plugin: https://github.com/TheFixerDevelopment/Eggwars-GenisysPro/releases/download/v1.0.0/EggWars_v1.phar
