### ISSUE TITLE
Team with X = 0

### ISSUE THREAD

**Issue by TheNewHEROBRINEX** [NL-4-DEVS/Eggwars#70]
If a team in the config has as X 0 the plugin will assume that the team doesn't exist due to the fact that the function empty returns true for 0 at https://github.com/NL-4-DEVS/Eggwars/blob/master/src/Driesboy/EggWars/EggWars.php#L256

**Comment by Driesboy** [comment]
i have no idea how to fix this

**Comment by TheNewHEROBRINEX** [comment]
Maybe you can use also isset or is_null but test first i'm not sure

**Comment by Driesboy** [comment]
Empty is also 0 in int so you are right but its fixed

Op 3-aug.-2017 21:42 schreef "TheNewHEROBRINEX" <notifications@github.com>:
