### ISSUE TITLE
drop sign doesn't work

### ISSUE THREAD

**Issue by ExaSonit** [NL-4-DEVS/Eggwars#71]
if i place a sign like generator, this doesn't drop anything when match starts, solve

**Comment by Driesboy** [comment]
generator
Diamond
broken

**Comment by ExaSonit** [comment]
generator
Diamond

Isn't correct?

**Comment by Driesboy** [comment]
normaly it need to work

**Comment by Driesboy** [comment]
you are using a fork of this plugin
forks are not supported
