### ISSUE TITLE
A little question

### ISSUE THREAD

**Issue by ExaSonit** [NL-4-DEVS/Eggwars#75]
/ew create <arena> etc... arena must be the world name?

**Comment by SuperKali** [comment]
You just need to enter the game map world and make the / ew create name that you decide

**Comment by ExaSonit** [comment]
Il reset della mappa funziona? Quanto tempo ci mette più o meno?

**Comment by SuperKali** [comment]
Immediatamente se usi una vps decente

**Comment by ExaSonit** [comment]
E se uso un server con massimo 256mb utilizzabili? (Non è una vps e nemmeno un server)

**Comment by SuperKali** [comment]
Credo che lagghi

**Comment by ExaSonit** [comment]
Apparte quello... Il problema è che non resetta mai hahaha

**Comment by SuperKali** [comment]
Che versione usi?

**Comment by ExaSonit** [comment]
Ho riadattato il plugin per pocketmine alpha6 perciò credo che gli errori gli abbia fatti io...

**Comment by SuperKali** [comment]
Attualmente il plugin e Aggiornato in alpha7

**Comment by ExaSonit** [comment]
molti server non vogliono aggiornare ecco perché l'ho dovuto necessariamente riportare ad alpha6

**Comment by ExaSonit** [comment]
mi spieghi come si imposta una eggwars, ovvero mi elenchi in ordine i comandi da eseguire?

**Comment by Driesboy** [comment]
koqhjpsodfkhjqmlksdjflmkqsdfjqmsdfkjqslmdfjqklsdfjmlqsdfqsdfqsdfqsd
