### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Herojhjh** [NL-4-DEVS/Eggwars#8]
[Tesseract] [14:13:06] CRITICAL> TypeError: "Argument 1 passed to pocketmine\item\Item::get() must be of the type integer, null given, called in /root/EggWars/plugins/Eggwars/src/Driesboy/EggWars/EggWars.php on line 599" (EXCEPTION) in "/src/pocketmine/item/Item" at line 330
[Tesseract] [14:13:06] CRITICAL> "Could not pass event 'pocketmine\event\entity\EntityDamageByEntityEvent' to 'EggWars v1': Argument 1 passed to pocketmine\item\Item::get() must be of the type integer, null given, called in /root/EggWars/plugins/Eggwars/src/Driesboy/EggWars/EggWars.php on line 599 on Driesboy\EggWars\EventListener

**Comment by KromeThirty30** [comment]
It is crashing on Tesseract, Try Pocketmine,Genisys or Bluelight!
