### ISSUE TITLE
the config shop.yml it's empty

### ISSUE THREAD

**Issue by SuperKali** [NL-4-DEVS/Eggwars#9]
The config shop.yml does not work when it is created and empty inside

**Comment by Driesboy** [comment]
ow oky

**Comment by SuperKali** [comment]
So if there are no items in the shop it creates that error

**Comment by Driesboy** [comment]
but did the shop.yml saves??

**Comment by SuperKali** [comment]
i tested on my server 
play.networkgames.eu port default join to test!

**Comment by SuperKali** [comment]
@Driesboy Nope
not save id item

**Comment by Driesboy** [comment]
Remove that link!!

Op 21-apr.-2017 12:07 schreef "SuperKali" <notifications@github.com>:

**Comment by Driesboy** [comment]
And is it saved???

Op 21-apr.-2017 12:06 schreef "SuperKali" <notifications@github.com>:

**Comment by SuperKali** [comment]
When I put the plugin on the server and enabled the server on the config shop.yml there is no id item so if i put them manually goes and saves them but does not automatically create

**Comment by Driesboy** [comment]
pmmp bug
